# Generated by Django 2.0.4 on 2018-04-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0004_auto_20180429_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
